replicaCount: 2

image:
  repository: us-east1-docker.pkg.dev/artful-fragment-458014-j4/demo-app/demo-app
  tag: latest
  pullPolicy: IfNotPresent

redis:
  host: 10.170.201.60
  port: 6379

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: demo-app-devoteam.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
