# Default values for python-app
replicaCount: 2

image:
  repository: us-central1-docker.pkg.dev/artful-fragment-458014-j4/demo-app/demo-app
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80
  targetPort: 8080

# Application configuration
app:
  port: 8080
  host: "0.0.0.0"
  environment: production

# Redis configuration
redis:
  host: "10.78.36.252"
  port: 6379
  db: 0

# Resource limits and requests
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Health check configuration
healthcheck:
  liveness:
    path: /
    initialDelaySeconds: 30
    periodSeconds: 10
  readiness:
    path: /
    initialDelaySeconds: 5
    periodSeconds: 5

# Namespace
namespace: "production"

# Pod annotations
podAnnotations: {}

# Security context
securityContext: {}

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Ingress configuration
ingress:
  enabled: true
  className: "gce"
  annotations:
    kubernetes.io/ingress.class: "gce"
    ingress.gcp.kubernetes.io/load-balancer-type: "External"
  hosts:
    - host: ""
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls: []