replicaCount: 3

image:
  repository: us-east1-docker.pkg.dev/artful-fragment-458014-j4/demo-app
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "demo-app-ip"
    networking.gke.io/managed-certificates: "demo-app-ssl"
    kubernetes.io/ingress.allow-http: "false"
  hosts:
    - host: your-domain.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

healthCheck:
  readinessProbe:
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  livenessProbe:
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

redis:
  enabled: true
  image:
    repository: bitnami/redis
    tag: 7.0.11
  password: "your-redis-password"

monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    labels:
      app: demo-app
