# Default values for devops-challenge-app
replicaCount: 3

image:
  repository: us-east1-docker.pkg.dev/artful-fragment-458014-j4/demo-app
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: "gce"
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "devops-challenge-ip"
    networking.gke.io/managed-certificates: "devops-challenge-ssl"
    kubernetes.io/ingress.allow-http: "false"
  hosts:
    - host: your-domain.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Application configuration
app:
  environment: "PROD"
  host: "0.0.0.0"
  port: 8080

# Redis configuration
redis:
  host: "redis-service"
  port: 6379
  db: 0
  password: "your-redis-password"

# Health check configuration
healthCheck:
  enabled: true
  path: /health
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 3

# Monitoring
monitoring:
  enabled: true
  serviceMonitor:
    enabled: false
    labels:
      app: devops-challenge-app
