replicaCount: 2

image:
  repository: us-east1-docker.pkg.dev/artful-fragment-458014-j4/demo-app/demo-app
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  host: "your-domain.com"
  managedCertificate: ""
  tls:
    enabled: false
    secretName: ""

resources: {}

livenessProbe:
  path: /
  port: 80
  initialDelaySeconds: 10
  periodSeconds: 10

redis:
  enabled: true
  host: "10.170.201.60"   # ← Replace with actual Redis IP from GCP
  port: 6379
