{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "python-app.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "python-app.fullname" . }}
  minReplicas: {{ default 1 .Values.autoscaling.minReplicas }}
  maxReplicas: {{ default 5 .Values.autoscaling.maxReplicas }}
  targetCPUUtilizationPercentage: {{ default 80 .Values.autoscaling.targetCPUUtilizationPercentage }}
{{- else }}
# HPA disabled
{{- end }}
