{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.secretName }}
type: Opaque
data:
  {{- range .Values.secret.gcpSecretManager.secrets }}
  {{ .key }}: {{ "{{ .secretId | b64enc }}" }}
  {{- end }}
{{- end }}