apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops-challenge-app.fullname" . }}-secret
  labels:
    {{- include "devops-challenge-app.labels" . | nindent 4 }}
type: Opaque
data:
  # Add any sensitive configuration here
  # REDIS_PASSWORD: {{ .Values.redis.password | b64enc | quote }}