name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: artful-fragment-458014-j4
  REGION: us-east1
  WORKLOAD_IDENTITY_PROVIDER: projects/447195453845/locations/global/workloadIdentityPools/github-actions-pool/providers/github-gke-terraform
  SERVICE_ACCOUNT: gke-terraform-service-account@artful-fragment-458014-j4.iam.gserviceaccount.com
  WORKING_DIR: infra/environment

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init & Apply
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          terraform init -backend-config="bucket=${{ env.PROJECT_ID }}-tf-state" -backend-config="prefix=devops-challenge"
          terraform apply -auto-approve

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: private-gke-cluster
          location: ${{ env.REGION }}

      - name: Build & Push Docker Image
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/demo-app/demo-app:latest .
          echo "${{ env.SERVICE_ACCOUNT }}" | docker login -u _json_key --password-stdin https://${{ env.REGION }}-docker.pkg.dev

      - name: Helm Deploy
        run: |
          helm upgrade --install demo-app ./charts/demo-app --set image.repository=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/demo-app/demo-app
