name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

  workflow_dispatch:

env:
  PROJECT_ID: artful-fragment-458014-j4
  REGION: us-east1
  WORKLOAD_IDENTITY_PROVIDER: projects/447195453845/locations/global/workloadIdentityPools/github-actions-pool/providers/devoteam-challenge
  SERVICE_ACCOUNT: gke-terraform-service-account@artful-fragment-458014-j4.iam.gserviceaccount.com
  WORKING_DIR: infra/environment
  CLUSTER_NAME: private-gke-cluster
  CLUSTER_LOCATION : us-east1
  REPOSITORY: demo-app
  IMAGE: demo-app


permissions:
  contents: read
  id-token: write # Required for requesting the JWT

jobs:
  authenticate:
    name: GCP Authentication
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      auth_status: ${{ steps.auth.outputs.auth_status || 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          project_id:                ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account:            ${{ env.SERVICE_ACCOUNT }}

  terraform-checks:
    name: Terraform Init & Validation
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    needs: authenticate
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          
      - name: Google Auth
        uses: 'google-github-actions/auth@v2'
        with:
          project_id:                ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account:            ${{ env.SERVICE_ACCOUNT }}
          
      - name: Terraform Cleanup
        run: rm -rf .terraform
        
      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: infra
        
      - name: Initialize Terraform
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}
        
      - name: Validate Terraform Configuration
        run: terraform validate
        working-directory: ${{ env.WORKING_DIR }}
        
      - name: Terraform Configuration Plan Report
        run: terraform plan
        working-directory: ${{ env.WORKING_DIR }}

  deploy-infrastructure:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    needs: terraform-checks
    environment: production  # Add environment for approval
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          
      - name: Google Auth
        uses: 'google-github-actions/auth@v2'
        with:
          project_id:                ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account:            ${{ env.SERVICE_ACCOUNT }}
          
      - name: Initialize Terraform
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}
        
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ${{ env.WORKING_DIR }}
        
      - name: Confirm Infrastructure Deployment
        run: |
          echo "Infrastructure deployment completed successfully!"
      
        
  test-apps:
    name: Test the app
    runs-on: ubuntu-latest
    needs: deploy-infrastructure
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r DevOps-Challenge-Demo-Code/requirements.txt
  
      - name: Run tests
        run: |
          python DevOps-Challenge-Demo-Code/tests/test.py

  build-and-push:
      needs: test-apps
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/main'
      outputs:
        image-tag: ${{ steps.build.outputs.image-tag }}
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: Google Auth
        uses: 'google-github-actions/auth@v2'
        with:
          project_id:                ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account:            ${{ env.SERVICE_ACCOUNT }}
  
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
  
      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker ${{ env.CLUSTER_LOCATION }}-docker.pkg.dev
  
      - name: Create Artifact Registry repository if it doesn't exist
        run: |
          gcloud artifacts repositories create ${{ env.REPOSITORY }} \
            --repository-format=docker \
            --location=${{ env.CLUSTER_LOCATION }} \
            --description="Docker repository for DevOps Challenge" || true
  
      - name: Build and push Docker image
        id: build
        working-directory: DevOps-Challenge-Demo-Code
        run: |
          IMAGE_TAG=${{ env.CLUSTER_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${GITHUB_SHA}
          IMAGE_TAG_LATEST=${{ env.CLUSTER_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:latest
          
          docker build -t $IMAGE_TAG -t $IMAGE_TAG_LATEST .
          docker push $IMAGE_TAG
          docker push $IMAGE_TAG_LATEST
          
          echo "image-tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
      # - name: Google Auth
      #   uses: google-github-actions/auth@v2
      #   with:
      #     project_id:                ${{ env.PROJECT_ID }}
      #     workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
      #     service_account:            ${{ env.SERVICE_ACCOUNT }}
      # - name: Set up GKE credentials
      #   uses: google-github-actions/get-gke-credentials@v2
      #   with:
      #     project_id:   ${{ env.PROJECT_ID }}
      #     cluster_name: ${{ env.CLUSTER_NAME }}
      #     location:     ${{ env.CLUSTER_LOCATION }}

      - name: Dry-run apply (server-side)
        run: |
          kubectl apply \
            --validate=false \
            --dry-run=server \
            -f https://raw.githubusercontent.com/GoogleCloudPlatform/microservices-demo/master/release/kubernetes-manifests.yaml

      - name: Show diff against live cluster
        run: |
          kubectl diff \
            --server-side \
            -f https://raw.githubusercontent.com/GoogleCloudPlatform/microservices-demo/master/release/kubernetes-manifests.yaml || echo "Differences found, but continuing workflow"
          
          
          
  deploy-applications:
    name: Deploy Applications
    runs-on: ubuntu-latest
    needs: test-apps
    environment: production  # Add environment for approval
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Google Auth
        uses: 'google-github-actions/auth@v2'
        with:
          project_id:                ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account:            ${{ env.SERVICE_ACCOUNT }}
  
      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          project_id:   ${{ env.PROJECT_ID }}
          cluster_name: ${{ env.CLUSTER_NAME }}
          location:     ${{ env.CLUSTER_LOCATION }}
          
      - name: Build & Push Docker Image
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/demo-app/demo-app:latest .
          echo "${{ env.SERVICE_ACCOUNT }}" | docker login -u _json_key --password-stdin https://${{ env.REGION }}-docker.pkg.dev

      - name: Helm Deploy
        run: |
          helm upgrade --install demo-app ./charts/demo-app --set image.repository=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/demo-app/demo-app
      - name: Deploy Applications
        run: |
          kubectl apply --validate=false -f https://raw.githubusercontent.com/GoogleCloudPlatform/microservices-demo/master/release/kubernetes-manifests.yaml
      
      - name: Get Load Balancer External IP
        run: |
          for i in {1..10}; do
            IP=$(kubectl get svc --field-selector spec.type=LoadBalancer -o jsonpath='{.items[0].status.loadBalancer.ingress[0].ip}')
            if [[ -n "$IP" ]]; then
              echo "External IP: $IP"
              exit 0
            fi
            echo "Attempt $i: no IP yet, sleeping..."
            sleep 15
          done
          echo "Timed out waiting for LoadBalancer IP" && exit 1
      
     
  
          
  notification:
    name: Failed pipeline notification
    runs-on: ubuntu-latest
    needs: [terraform-checks, test-apps, deploy-infrastructure, deploy-applications]
    if: ${{ always() && (contains(join(needs.*.result, ','), 'failure') || contains(join(needs.*.result,','), 'cancelled')) }}
    steps:
      - name: Notify on Slack
        run: echo "Sending  message about failed pipeline..."
  


